---
- name: Clone tooling repo into temp folder
  become: true
  ansible.builtin.git:
    repo: https://github.com/Sheviantos1/tooling.git
    dest: /tmp/tooling
    force: yes

- name: Copy content from /tmp/tooling/html to /var/www/html
  become: true
  ansible.builtin.copy:
    src: /tmp/tooling/html/
    dest: /var/www/html/
    owner: apache
    group: apache
    mode: '0755'
    remote_src: yes

- name: Restart Apache
  become: true
  ansible.builtin.service:
    name: httpd
    state: restarted
